# Generated by Django 4.2.7 on 2025-03-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver_name', models.CharField(max_length=100)),
                ('carrier_name', models.CharField(max_length=100)),
                ('truck_number', models.CharField(max_length=50)),
                ('trailer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('start_odometer', models.IntegerField(default=0)),
                ('end_odometer', models.IntegerField(default=0)),
                ('total_miles', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cycle_hours', models.FloatField(default=0)),
                ('total_distance', models.FloatField(default=0)),
                ('total_duration', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_current', to='api.location')),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_dropoff', to='api.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_pickup', to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('drive', 'Driving'), ('rest', 'Rest'), ('sleep', 'Sleep'), ('fuel', 'Fuel'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=10)),
                ('distance', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_as_end', to='api.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_as_start', to='api.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty Not Driving')], max_length=3)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.dailylog')),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='api.trip'),
        ),
    ]
