# Generated by Django 4.2.7 on 2025-03-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty Not Driving')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='routesegment',
            name='segment_type',
            field=models.CharField(choices=[('drive', 'Driving'), ('rest', 'Rest'), ('sleep', 'Sleep'), ('fuel', 'Fuel'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='routesegment',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['trip', 'date'], name='api_dailylo_trip_id_ee3f58_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='api_locatio_latitud_670fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['daily_log', 'status'], name='api_logentr_daily_l_547921_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['start_time', 'end_time'], name='api_logentr_start_t_0ff385_idx'),
        ),
        migrations.AddIndex(
            model_name='routesegment',
            index=models.Index(fields=['trip', 'segment_type'], name='api_routese_trip_id_a81441_idx'),
        ),
        migrations.AddIndex(
            model_name='routesegment',
            index=models.Index(fields=['start_time', 'end_time'], name='api_routese_start_t_ea6af1_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['-created_at'], name='api_trip_created_24deb9_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_time', 'end_time'], name='api_trip_start_t_d0e9c9_idx'),
        ),
    ]
