# Generated by Django 4.2.7 on 2025-03-17 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dailylog_date_alter_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='end_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_as_end', to='api.location'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_as_start', to='api.location'),
        ),
    ]
